excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://abigailjane.github.io
title: I'm Abigail Jane 
tagline: A log of everyday life
description: Catch me on the flip side enjoying this amazing life. 
paginate: 5